import duckdb

con = duckdb.connect("swiggy_reviews.duckdb")

con.execute("""
CREATE TABLE IF NOT EXISTS topics (
    topic_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    canonical_name VARCHAR,
    created_on DATE
)
""")

con.execute("""
CREATE TABLE IF NOT EXISTS topic_variants (
    variant_text VARCHAR,
    topic_id INTEGER
)
""")

con.execute("""
CREATE TABLE IF NOT EXISTS daily_topic_counts (
    topic_id INTEGER,
    review_date DATE,
    count INTEGER
)
""")

con.close()
